

export const environment = {
  production: false,
    Login:'userlogin',
    Register:'userregister',
    Alluser:'alluser',
    UserbyId:'userbyid',
    Updateuser:'updateuserbyid',
    timeline:'timeline',
    like:'like',
    postbyuserid:'postbyuserid',
    createPost:'userpost',
    deletePost:'deletepost',
    commentPost:'comment',
    allUser:'alluser',
    userByID:'userbyid',
    changePassword:'Changepassword',
    userFollow:'userfollow',
    userUnfollow:"userunfollow",
    forgotPassword:'otpsend',
    commentDelete:'comment/delete',
    commentEdit:'comment/edit',
    addreply:'comment/addreply',
    editReply:'comment/editreply',
    deleteReply:'comment/deletereply',
    removeFollower:'removefollower',
    newChat:'addnewchat',
    chatlist:'chatlist',
    sendMessage:'sendmessage',
    chathistory:'messagechathistory',
    socketUrl:'http://localhost:5000',
     AWS_ACCESS_KEY:'AKIAZ6L3DB2TH46CJ5WN',
     AWS_KEY:'DXadDLL9Co80Vb+3OmCknsiVoqZaInEMxNF5qox3',
     AWS_ACCESS_KEY2:'AKIAZ6L3DB2TDT62V6JD',
  AWS_KEY2:'xPJ18yOdtb5CKXXersHVjjdNc0SqPrkoQVptIHsB'
};

